### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by shishirong** [notisrac/FileToCArray#3]
file size 143kB

**Comment by notisrac** [comment]
Could you please provide a bit more info on what you did to get the error?
File (something I can reproduce the error with), settings, what is the exact error message, and where did it displayed the error, etc.

**Comment by shishirong** [comment]
It is crashed when I click ‘Copy to clipboard’ button.
![image](https://github.com/notisrac/FileToCArray/assets/16620315/f098ec9a-e6ef-4272-b0c8-4b66e1b632f4)

test file:
[test.zip](https://github.com/notisrac/FileToCArray/files/11890250/test.zip)

**Comment by shishirong** [comment]
I'm using msedge browser,  It is OK when I use `private mode`，Maybe it's caused by some browser extensions.
