### ISSUE TITLE
signed char mode doesn't work

### ISSUE THREAD

**Issue by wothke** [notisrac/FileToCArray#4]
see https://notisrac.github.io/FileToCArray/

When selecting "Code format" "Decimal (000)" and NOT  "unsigned" (i.e. it should be signed values) and
"Data type" "char" or "int8_t", then the Result should NEVER contain values like 250, 202, etc - since these should be 
negative numbers! (or there should at least be an option to allow that output)

**Comment by notisrac** [comment]
Currently the "static", "const", "unsigned", "Data type", "char" and "PROGMEM" settings only modify which strings get generated into the output.  There is no other validation or logic behind them.
But pull requests are always welcome!

**Comment by wothke** [comment]
well, it seems stupid to rely on C's overflow handling and produce data that is out of range of the specified data type.. I guess I'll just use a different tool then
